import { invoke } from '@tauri-apps/api/core';

export type LegalDocumentId = 'privacy' | 'terms' | 'risk';
export type LegalDocument = { id: LegalDocumentId; title: string; eyebrow: string; version: string; sections: Array<{ heading: string; body: string[] }> };

export const LEGAL_DOCUMENTS: Record<LegalDocumentId, LegalDocument> = {
  privacy: { id:'privacy', title:'Hedge OS Privacy Policy', eyebrow:'Privacy policy', version:'Draft · 2026-09-12', sections:[
    {heading:'Effective date',body:['Effective Date: [DATE] · Last Updated: [DATE]','This Privacy Policy explains how [LEGAL COMPANY NAME], operating Hedge OS, collects, uses, stores, and discloses information when you use the Hedge OS website, application, browser extension, trading integrations, and related services.']},
    {heading:'Information we may collect',body:['Depending on the features you use, we may process account information, preferences, support communications, technical diagnostics, browser and device information, timestamps, connection status, and security events.','To provide trading functionality, Hedge OS may process broker or trading-platform identifiers, instrument symbols, positions, orders, fills, balances, order status, execution information, market data, risk settings, hedge parameters, and other information required to display, calculate, transmit, monitor, modify, or cancel trading instructions.']},
    {heading:'Credentials and local processing',body:['Hedge OS may require authentication information or authorization tokens to communicate with supported third parties. Where technically possible, sensitive credentials should be processed locally or exchanged directly with the applicable third party rather than stored by Hedge OS.','Hedge OS does not obtain ownership of your brokerage accounts, funds, positions, or credentials. You remain responsible for protecting your credentials and account security.']},
    {heading:'Use and disclosure',body:['We may process information to provide and maintain the Services; connect supported platforms; calculate and transmit configured instructions; synchronize activity; detect execution mismatches; provide support; maintain security; prevent fraud; improve the Services; comply with law; and enforce our agreements.','We may disclose information to providers reasonably necessary to operate the Services, or where required by law or reasonably necessary to address fraud, security threats, or unlawful activity. We do not sell personal information for monetary consideration.']},
    {heading:'Retention, security, and rights',body:['We retain information only as long as reasonably necessary for the purposes collected, security, transaction records, disputes, and legal obligations. Device-only information may disappear when you uninstall the app or extension or clear local storage.','No computer system, browser extension, transmission, trading platform, or storage system is completely secure. Subject to law, you may request access, correction, withdrawal of consent, or information about our privacy practices at [PRIVACY EMAIL].']},
    {heading:'Third parties and changes',body:['Third-party brokers, exchanges, prop firms, market-data providers, and platforms are independent and governed by their own terms and privacy policies. Hedge OS is not responsible for their data practices, availability, accuracy, privacy, security, or execution practices.','We may update this policy as the Services evolve. Material changes will be communicated as required by law. Questions may be directed to [LEGAL COMPANY NAME], [ADDRESS], [EMAIL].']},
  ]},
  terms: { id:'terms', title:'Hedge OS Terms of Service', eyebrow:'Terms of service', version:'Draft · 2026-09-12', sections:[
    {heading:'Agreement and nature of service',body:['These Terms are a legally binding agreement between you and [LEGAL COMPANY NAME], operating Hedge OS. By creating an account, using the application or extension, connecting a trading account, or clicking an acceptance control, you agree. If you do not agree, do not use Hedge OS or connect a trading account.','Hedge OS provides trading workflow automation, order coordination, position monitoring, hedge calculations, risk-management automation, and communication with supported third-party platforms. When configured and authorized by you, it may generate or transmit orders.']},
    {heading:'No brokerage or advice relationship',body:['Hedge OS is not your broker, futures commission merchant, exchange, clearing firm, custodian, bank, or prop trading firm. It does not custody funds or control third-party infrastructure, matching engines, margin, liquidations, market data, restrictions, or execution practices.','Nothing in Hedge OS is personalized investment, commodity trading, financial, legal, or tax advice, or a recommendation or solicitation to trade. Software-generated calculations, ratios, simulations, alerts, analytics, and estimates may be incomplete, inaccurate, delayed, or unsuitable for your circumstances.']},
    {heading:'User-controlled trading and risk',body:['You authorize Hedge OS to communicate with accounts and platforms you voluntarily connect. Authorized functionality may transmit, modify, replace, cancel, or close orders and positions. You remain solely responsible for every connected account and every resulting order or position.','Electronic and automated trading can fail, including through defects, outages, stale data, delayed messages, API or authentication failures, rejected, partial, duplicate, missed, delayed, or incorrectly priced orders, synchronization failures, slippage, gaps, and third-party changes. A hedge may fail to execute, execute late or partially, or fail to offset a loss.']},
    {heading:'Third parties and availability',body:['Third parties may change interfaces, APIs, authentication, market data, order-entry systems, account rules, or permitted uses without notice. Hedge OS does not guarantee compatibility with any broker, prop firm, exchange, platform, browser, or service. You must comply with all third-party agreements and rules.','The Services are provided “AS IS” and “AS AVAILABLE” to the maximum extent permitted by law. We do not warrant uninterrupted, error-free, secure, accurate, complete, profitable, or suitable service. Historical and simulated results do not guarantee future performance.']},
    {heading:'Assumption of risk and responsibilities',body:['Trading futures, derivatives, leveraged instruments, securities, digital assets, and other financial products can result in rapid, substantial, or complete losses, and may exceed the amount deposited. You voluntarily assume all risks of your trading activity and authorized use of Hedge OS.','You are responsible for capital and margin, verifying symbols, quantities, prices, directions, settings and accounts, monitoring orders and positions, maintaining independent account access, protecting credentials, and complying with broker and prop-firm rules.']},
    {heading:'Liability, law, and electronic acceptance',body:['To the maximum extent permitted by law, Hedge OS and [LEGAL COMPANY NAME] are not liable for indirect, incidental, special, exemplary, punitive, or consequential damages, including lost profits, trading losses, lost opportunities, or losses arising from third-party services. Aggregate liability will not exceed the greater of amounts paid during the preceding three months or CAD $100. Nothing excludes liability that cannot legally be excluded.','These Terms are governed by the laws of Ontario and applicable federal Canadian law. Clicking “I Agree,” “Accept,” “Connect Account,” or another clearly designated acceptance control constitutes electronic acceptance. The Privacy Policy and Trading Risk Acknowledgment form part of this agreement.']},
  ]},
  risk: { id:'risk', title:'Trading Risk Acknowledgment & User Consent', eyebrow:'Trading risk', version:'Draft · 2026-09-12', sections:[
    {heading:'Important disclosure',body:['Read this document before connecting any trading account or enabling trading. Hedge OS is software, not your broker, fiduciary, investment adviser, financial adviser, or guarantor. You control whether to connect an account, activate automation, choose risk parameters, and permit orders.']},
    {heading:'Orders can affect real money',body:['When authorized, Hedge OS may transmit, modify, cancel, replace, or close orders and positions. These actions can affect real money. You may lose some or all of the money in your account and may incur losses greater than your initial deposit where applicable.']},
    {heading:'A hedge is not guaranteed protection',body:['A hedge is not risk-free. Intended offsetting positions may differ in fills, prices, timing, liquidity, fees, specifications, market movements, or outcomes. A hedge may fail to offset the loss it was intended to hedge.','Orders intended to execute together may execute at different times, partially fill, be rejected, cancelled, delayed, duplicated, or execute at an unexpected price. You accept resulting basis risk, execution risk, slippage risk, and temporary unhedged exposure.']},
    {heading:'Software and third-party failures',body:['Hedge OS may experience defects, loss of connectivity, stale prices, incorrect market data, synchronization errors, browser-extension failures, website or API changes, websocket failures, incorrect account or symbol detection, rejected orders, duplicate instructions, delayed instructions, and other unexpected behaviour.','Brokers, exchanges, prop firms, platforms, internet providers, and data vendors operate independently. Hedge OS cannot guarantee their availability, accuracy, rules, execution, or behaviour.']},
    {heading:'Your responsibility',body:['Hedge ratios, loss calculations, drawdown calculations, payout estimates, simulations, backtests, and other outputs may rely on assumptions, and actual results can differ materially. Automated trading does not eliminate your responsibility to monitor your accounts or maintain direct platform access.','By enabling trading, you authorize Hedge OS to electronically communicate the instructions and automation you configure. You may revoke authorization by disabling functionality or disconnecting the account, subject to instructions already transmitted.']},
    {heading:'Acceptance of financial risk',body:['TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU ACCEPT THE FINANCIAL RISKS ARISING FROM YOUR TRADING DECISIONS AND AUTHORIZED USE OF HEDGE OS, INCLUDING THE POSSIBILITY OF COMPLETE LOSS OF TRADING CAPITAL. Hedge OS makes no promise that losses will be prevented, reimbursed, recovered, hedged, or limited.']},
  ]},
};

export type TradingRiskAcceptance = { id: string; documentId: 'risk'; version: string; acceptedAt: string; checkboxes: [true, true, true]; metadata: { source: string } };
export type TermsAcceptance = { id: string; documentId: 'terms'; version: string; acceptedAt: string; metadata: { source: string } };
const riskKey='hedge-os:trading-risk-acceptance';
const termsKey='hedge-os:terms-acceptance';
const historyKey='hedge-os:legal-acceptance-history';
const tauri=()=>Boolean((window as unknown as {__TAURI_INTERNALS__?:unknown}).__TAURI_INTERNALS__);
export function getTradingRiskAcceptance(): TradingRiskAcceptance | null { try { const value=JSON.parse(localStorage.getItem(riskKey)??'null'); return value?.version===LEGAL_DOCUMENTS.risk.version ? value : null; } catch { return null; } }
export function hasTradingRiskConsent() { return Boolean(getTradingRiskAcceptance()); }
export function getTermsAcceptance(): TermsAcceptance | null { try { const value=JSON.parse(localStorage.getItem(termsKey)??'null'); return value?.version===LEGAL_DOCUMENTS.terms.version ? value : null; } catch { return null; } }
export function hasTermsConsent() { return Boolean(getTermsAcceptance()); }
export async function submitTermsConsent() {
  const acceptance: TermsAcceptance={id:crypto.randomUUID(),documentId:'terms',version:LEGAL_DOCUMENTS.terms.version,acceptedAt:new Date().toISOString(),metadata:{source:'terms-dialog'}};
  if(tauri()) await invoke('record_legal_acceptance',{acceptance});
  else { const history=JSON.parse(localStorage.getItem(historyKey)??'[]') as Array<TradingRiskAcceptance|TermsAcceptance>; localStorage.setItem(historyKey,JSON.stringify([...history,acceptance])); }
  localStorage.setItem(termsKey,JSON.stringify(acceptance));
  return acceptance;
}
export async function submitTradingRiskConsent() {
  const acceptance: TradingRiskAcceptance={id:crypto.randomUUID(),documentId:'risk',version:LEGAL_DOCUMENTS.risk.version,acceptedAt:new Date().toISOString(),checkboxes:[true,true,true],metadata:{source:'trading-risk-dialog'}};
  if(tauri()) await invoke('record_legal_acceptance',{acceptance});
  else { const history=JSON.parse(localStorage.getItem(historyKey)??'[]') as TradingRiskAcceptance[]; localStorage.setItem(historyKey,JSON.stringify([...history,acceptance])); }
  // This cache is only used to gate the current local client. Tauri persists the
  // authoritative submission in its SQLite application database.
  localStorage.setItem(riskKey,JSON.stringify(acceptance));
  return acceptance;
}
